### ISSUE TITLE
Add YAML

### ISSUE THREAD

**Issue by jgroom33** [quicktype/quicktype-vscode#15]
Though yaml is not a language, it would be nice to have this as an option.

**Comment by schani** [comment]
Do you mean as an input?

**Comment by jgroom33** [comment]
as an output.  currently, I'm using websites like: https://www.json2yaml.com/ to do quick conversions.
Looks like this should be implemented in quicktype though

**Comment by schani** [comment]
No, this is not a good fit for quicktype.  quicktype deals with data types, not with the data itself.

Also, there are already VSCode extensions that seem to do this, [such as this one](https://marketplace.visualstudio.com/items?itemName=tuxtina.json2yaml).

**Comment by jgroom33** [comment]
thx... hadnt found that
