### ISSUE TITLE
dart support

### ISSUE THREAD

**Issue by crazecoder** [quicktype/quicktype-vscode#18]
Will it support dart in the future?

**Comment by csells** [comment]
yeah! hey! I'd like Dart support right inside my VSCode! QT already supports Dart; can we get it into the extension?

**Comment by sachq** [comment]
https://app.quicktype.io/

**Comment by csells** [comment]
Right. It would be great if the extension supported Dart.

**Comment by dvdsgl** [comment]
Dart is supported.

**Comment by lukas-h** [comment]
@dvdsgl Could you update the README accordingly?
