### ISSUE TITLE
Default keybinding clashes with Markdown preview

### ISSUE THREAD

**Issue by itowlson** [quicktype/quicktype-vscode#19]
The default keybinding `Ctrl+Shift+V` clashes with the Markdown preview key combination.  When a user has this extension installed, and tries to preview a Markdown document, VS Code instead shows a language dropdown, which is a bit confusing!

I believe this can be addressed without disruption by changing the default keybinding when clause to `editorTextFocus && editorLangId != 'markdown'`, as users will never need to use the `Paste JSON as Code` command in Markdown documents.

**Comment by xgdgsc** [comment]
Please update the extension at marketplace for this.
