### ISSUE TITLE
cant use with remote wsl  Could not get clipboard contents

### ISSUE THREAD

**Issue by nziomini** [quicktype/quicktype-vscode#24]
cant use with remote wsl   Could not get clipboard contents

**Comment by 3nuc** [comment]
Same here. I think #22 fixes this?

Steps to reproduce:
1. Copy any JSON from eg. notepad
2. Go to VS Code while using WSL (run `code` while in wsl.exe terminal for example)
3. CTRL+SHIFT+P and run "Paste JSON as Code" command
4. In bottom right you'll get standard vscode error notification like "Could not get clipboard contents". 

The only thing I could find in the logs is in "Log (Remote extension)":
```
[2020-06-01 10:55:57.534] [exthost] [info] ExtensionService#_doActivateExtension quicktype.quicktype {"startup":false,"extensionId":{"value":"quicktype.quicktype","_lower":"quicktype.quicktype"},"activationEvent":"onCommand:quicktype.pasteJSONAsTypes"}
[2020-06-01 10:55:57.535] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/artur/.vscode-server-insiders/extensions/quicktype.quicktype-12.0.46/out/src/extension
```

**Comment by dvdsgl** [comment]
Fixed by #22. You should have an update soon.

**Comment by ddieppa** [comment]
I am still having this issue, any update on this?

**Comment by MejanH** [comment]
still not working, any update?

**Comment by hichemfantar** [comment]
Having this problem on WLS1

**Comment by jtnidrizi** [comment]
I have the same issue in WSL 2

**Comment by hichemfantar** [comment]
It appears this extension was abandoned.
Last update was in 2018.

**Comment by N7K4** [comment]
[Iteresting post about generell issues with clipboard between host and WSL](https://stuartleeks.com/posts/vscode-devcontainer-clipboard-forwarding/)

**Comment by sweetarebero** [comment]
https://giters.com/quicktype/quicktype-vscode/issues/29
This one worked for me: https://marketplace.visualstudio.com/items?itemName=doggy8088.quicktype-refresh
