### ISSUE TITLE
Could you provide details on the theme for vscode shown in the screenshot?

### ISSUE THREAD

**Issue by goosenphil** [quicktype/quicktype-vscode#6]
Hi, I'm curious which theme you're using for vscode as shown in the gif of the README.

Also, how did you make the top search bar so big?

**Comment by schani** [comment]
That's the default configuration of the child VSCode instance that runs when you're debugging a VSCode extension.  I have no idea where it's specified.

**Comment by dvdsgl** [comment]
The theme is Material. We zoomed the window with Command-Plus.
