### ISSUE TITLE
error "Clipboard does not contain valid JSON" for any JSON

### ISSUE THREAD

**Issue by schani** [quicktype/quicktype-vscode#8]
By [chopeen](https://github.com/chopeen) ([original](https://github.com/quicktype/quicktype/issues/904)):

I am getting the same error for any JSON content I try, even the Pokémon JSON from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=quicktype.quicktype).

The Output pane does not show any additional details.

---

Extension version: 10.24
VS Code version: 1.24.1

**Comment by schani** [comment]
I can't reproduce this.

**Comment by chopeen** [comment]
I checked one more time; I put a [short recording at Imgur](https://i.imgur.com/P7AcmxN.gif).

**Comment by schani** [comment]
Thank you, that is very useful.  Is this with the latest version of the extension?

You can debug the extension if you clone the repo, open it in VSCode, and then use the debugger to start a debugging instance of VSCode.  If you'd like to do that and need some help, please join us [on Slack](https://slack.quicktype.io).

**Comment by schani** [comment]
We jumped from 10.0.24 to 11.0.6 yesterday, so your original comment was correct.

**Comment by schani** [comment]
I'm sorry, I referenced the wrong issue in my PR, but I suspect that it might fix this one, too.  11.0.7 should land soon.  Could you please test it?

**Comment by schani** [comment]
Hurray!  Thank you! :-)
